<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LPDEV01" failures="0" tests="6" name="mainPackage.RunnerClass" time="489.794" errors="1" timestamp="2024-05-27T14:47:30 IST" skipped="0">
  <testcase classname="mainPackage.RunnerClass" name="testMethod" time="97.673"/>
  <system-out/>
  <testcase classname="mainPackage.RunnerClass" name="testMethod" time="97.971"/>
  <system-out/>
  <testcase classname="mainPackage.RunnerClass" name="testMethod" time="99.025"/>
  <system-out/>
  <testcase classname="mainPackage.RunnerClass" name="testMethod" time="97.409"/>
  <system-out/>
  <testcase classname="mainPackage.RunnerClass" name="testMethod" time="97.716"/>
  <system-out/>
  <testcase classname="mainPackage.RunnerClass" name="failedCasesRunMethod" time="0.000">
    <error message="
Data Provider public java.lang.Object[][] mainPackage.RunnerClass.failedData() returned a null value" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
Data Provider public java.lang.Object[][] mainPackage.RunnerClass.failedData() returned a null value
at org.testng.internal.invokers.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:159)
at org.testng.internal.Parameters.handleParameters(Parameters.java:803)
at org.testng.internal.Parameters.handleParameters(Parameters.java:728)
at org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)
at org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:924)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- failedCasesRunMethod -->
  <system-out/>
</testsuite> <!-- mainPackage.RunnerClass -->
